
// export const heroSectionData = {
//     carouselItems: [
//       {
//         id: '1',
//         imageUrl: '/unb.png', // Desktop image
//         mobileImageUrl: 'https://i.postimg.cc/xTyzJyTm/Screenshot-2025-06-27-155612-1.png', // Mobile image
//         title: 'Master IIT-JEE Advanced',
//         description: 'Ace your IIT-JEE with our comprehensive course!',
//         ctaText: 'Enroll Now',
//         ctaLink: '/courses/featured-iitjee-01',
//         dataAiHint: "iitjee online course",
//       },
//       {
//         id: '2',
//         imageUrl: '/geek.png',
//         title: 'NEET Biology Bootcamp',
//         description: 'Unlock your potential with this in-depth course!',
//         ctaText: 'Enroll Now',
//         ctaLink: '/courses/featured-neet-01',
//         dataAiHint: "neet medical course",
//       },
//       {
//         id: '3',
//         imageUrl: '/pb.png',
//         title: 'NEET Biology Bootcamp',
//         description: 'Unlock your potential with this in-depth course!',
//         ctaText: 'Enroll Now',
//         ctaLink: '/courses/featured-neet-01',
//         dataAiHint: "neet medical course",
//       },
//     ],
//     rightBanner: {
//       imageUrl: 'https://i.postimg.cc/nhsP0CSS/Screenshot-2025-06-14-144740.png',
//       // title: 'UPSC CSE Prep',
//       // description: 'Pre-Order Now',
//       // ctaText: 'Pre-Order',
//       // ctaLink: '/courses/featured-gov-01',
//       // bgColor: 'bg-[--primary-blue]',
//       // dataAiHint: "upsc government exam",
//       title: '',
//       ctaText: '',
//       ctaLink: '',
//       bgColor: '',
//       dataAiHint: "",
//     },
//     promoCard: {
//       imageUrl: 'https://static.pw.live/5eb393ee95fab7468a79d189/ADMIN/e5a74b05-f425-4259-b1de-d6bde25e2daa.jpg',
//       // title: 'Special Offer: 50% Off!',
//       // ctaText: 'Claim Now',
//       // ctaLink: '/offers/special',
//       // dataAiHint: "online learning offer",
//          title: '',
//       ctaText: '',
//       ctaLink: '',
//       dataAiHint: "",
//     },
//     bottomBanners: [
//         {
//         imageUrl: 'https://i.postimg.cc/jjMn2StK/Screenshot-2025-06-14-145131.png',
//         // title: 'Udemy',
//         // ctaText: 'Browse',
//         // ctaLink: '/courses?platform=udemy',
//         // bgColor: 'bg-[--primary-blue]',
//         // dataAiHint: "udemy online learning",
//         title: '',
//         ctaText: '',
//         ctaLink: '',
//         bgColor: '',
//         dataAiHint: "",
//       },
//       {
//         imageUrl: 'https://i.postimg.cc/05YKFsB8/Screenshot-2025-06-14-145642.png',
//         // title: 'Coursera',
//         // ctaText: 'Browse',
//         // ctaLink: '/courses?platform=coursera',
//         // bgColor: 'bg-[--accent-teal]',
//         // dataAiHint: "coursera online platform",
//         title: '',
//         ctaText: '',
//         ctaLink: '',
//         bgColor: '',
//         dataAiHint: "",
//       },
//       {
//         imageUrl: 'https://i.postimg.cc/m2kMHMhq/Screenshot-2025-06-14-143916-1.png',
//         // title: 'Business Courses',
//         // ctaText: 'Explore',
//         // ctaLink: '/courses?category=business',
//         // bgColor: 'bg-[--secondary-purple]',
//         // dataAiHint: "business finance chart",
//         title: '',
//         ctaText: '',
//         ctaLink: '',
//         bgColor: '',
//         dataAiHint: "",
//       },
//       {
//         imageUrl: 'https://i.postimg.cc/sDs7DqRV/Screenshot-2025-06-14-142944-1.png',
//         // title: 'Tech Courses',
//         // ctaText: 'Explore',
//         // ctaLink: '/courses?category=computer-science',
//         // bgColor: 'bg-[--accent-teal]',
//         // dataAiHint: "tech course computer",
//         title: '',
//         ctaText: '',
//         ctaLink: '',
//         bgColor: '',
//         dataAiHint: "",
//       },
//     ],
//   };


// Complete Hero Section Data with all spaces filled
export const heroSectionData = {
  carouselItems: [
    {
      id: '1',
      imageUrl: '/xxxx.jpg', // Desktop image
      mobileImageUrl: 'https://i.postimg.cc/xTyzJyTm/Screenshot-2025-06-27-155612-1.png', // Mobile image
      title: 'Master IIT-JEE Advanced',
      description: 'Ace your IIT-JEE with our comprehensive course!',
      ctaText: 'Enroll Now',
      ctaLink: '/courses/featured-iitjee-01',
      dataAiHint: "iitjee online course",
    },
    {
      id: '2',
      imageUrl: '/geek.png',
      mobileImageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&h=250&fit=crop&crop=center',
      title: 'NEET Biology Bootcamp',
      description: 'Unlock your potential with this in-depth course!',
      ctaText: 'Enroll Now',
      ctaLink: '/courses/featured-neet-01',
      dataAiHint: "neet medical course",
    },
    {
      id: '3',
      imageUrl: '/pwwww.png',
      mobileImageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=250&fit=crop&crop=center',
      title: 'NEET Biology Bootcamp',
      description: 'Unlock your potential with this in-depth course!',
      ctaText: 'Enroll Now',
      ctaLink: '/courses/featured-neet-01',
      dataAiHint: "neet medical course",
    },
    // Additional carousel items to fill space
    // {
    //   id: '4',
    //   imageUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=1200&h=480&fit=crop&crop=center',
    //   mobileImageUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=600&h=250&fit=crop&crop=center',
    //   title: 'Foundation Course 2026',
    //   description: 'Build strong fundamentals for competitive exams',
    //   ctaText: 'Start Learning',
    //   ctaLink: '/courses/foundation-2026',
    //   dataAiHint: "foundation course students",
    // },
    // {
    //   id: '5',
    //   imageUrl: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=1200&h=480&fit=crop&crop=center',
    //   mobileImageUrl: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=600&h=250&fit=crop&crop=center',
    //   title: 'Board Exam Excellence',
    //   description: 'Score 95+ in your board examinations',
    //   ctaText: 'Join Now',
    //   ctaLink: '/courses/board-exam-prep',
    //   dataAiHint: "board exam preparation",
    // },
  ],
  
  // Fill the 3/4 width empty space on desktop
  mainContentBanners: [
    {
      imageUrl: '/biaa.png',
      title: 'Live Classes Starting Soon',
      description: 'Interactive sessions with top educators',
      ctaText: 'Register Free',
      ctaLink: '/live-classes',
      bgColor: 'bg-gradient-to-r from-blue-600 to-purple-600',
      dataAiHint: "live online classes",
    },
    {
      imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=300&fit=crop&crop=center',
      title: 'Free Mock Test Series',
      description: 'Practice with latest exam patterns',
      ctaText: 'Take Test',
      ctaLink: '/mock-tests',
      bgColor: 'bg-gradient-to-r from-green-600 to-teal-600',
      dataAiHint: "mock test exam preparation",
    },
    {
      imageUrl: '/aa.png',
      title: 'Study Material Hub',
      description: 'Download PDFs, notes and practice sheets',
      ctaText: 'Access Now',
      ctaLink: '/study-materials',
      bgColor: 'bg-gradient-to-r from-orange-600 to-red-600',
      dataAiHint: "study materials books",
    },
  ],

  rightBanner: {
    imageUrl: 'https://i.postimg.cc/nhsP0CSS/Screenshot-2025-06-14-144740.png',
    title: '',
    ctaText: '',
    ctaLink: '/courses/upsc-prep',
    bgColor: '',
    dataAiHint: "upsc preparation banner",
  },
  
  promoCard: {
    imageUrl: 'https://static.pw.live/5eb393ee95fab7468a79d189/ADMIN/e5a74b05-f425-4259-b1de-d6bde25e2daa.jpg',
    title: '',
    ctaText: '',
    ctaLink: '/special-offers',
    dataAiHint: "special offer promotion",
  },

  bottomBanners: [
    {
      imageUrl: 'https://i.postimg.cc/jjMn2StK/Screenshot-2025-06-14-145131.png',
      title: '',
      ctaText: '',
      ctaLink: '/courses/typescript-tutorial',
      bgColor: '',
      dataAiHint: "typescript programming course",
    },
    {
      imageUrl: 'https://i.postimg.cc/05YKFsB8/Screenshot-2025-06-14-145642.png',
      title: '',
      ctaText: '',
      ctaLink: '/courses/cyber-security',
      bgColor: '',
      dataAiHint: "cyber security course",
    },
    {
      imageUrl: 'https://i.postimg.cc/m2kMHMhq/Screenshot-2025-06-14-143916-1.png',
      title: '',
      ctaText: '',
      ctaLink: '/courses/data-science',
      bgColor: '',
      dataAiHint: "data science analytics",
    },
    {
      imageUrl: 'https://i.postimg.cc/sDs7DqRV/Screenshot-2025-06-14-142944-1.png',
      title: '',
      ctaText: '',
      ctaLink: '/upsc-essentials',
      bgColor: '',
      dataAiHint: "upsc essentials course",
    },
  ],

  // Additional banners to fill more space
  additionalPromoBanners: [
    // {
    //   imageUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=400&h=200&fit=crop&crop=center',
    //   title: '',
    //   ctaText: '',
    //   ctaLink: '/one-on-one-mentorship',
    //   dataAiHint: "mentorship program",
    // },
    // {
    //   imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=200&fit=crop&crop=center',
    //   title: '',
    //   ctaText: '',
    //   ctaLink: '/scholarship-program',
    //   dataAiHint: "scholarship opportunity",
    // },
    // {
    //   imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=200&fit=crop&crop=center',
    //   title: '',
    //   ctaText: '',
    //   ctaLink: '/career-guidance',
    //   dataAiHint: "career counseling",
    // },
    // {
    //   imageUrl: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=400&h=200&fit=crop&crop=center',
    //   title: '',
    //   ctaText: '',
    //   ctaLink: '/success-stories',
    //   dataAiHint: "student success stories",
    // },
  ],
};