export const stateToHcKey: { [key: string]: string } = {
    'Tamil Nadu': 'in-tn',
    'Puducherry': 'in-py',
    'Himachal Pradesh': 'in-hp',
    'Sikkim': 'in-sk',
    'Delhi': 'in-dl',
    'Uttar Pradesh': 'in-up',
    'Haryana': 'in-hr',
    'Punjab': 'in-pb',
    'Chandigarh': 'in-ch',
    'Rajasthan': 'in-rj',
    'Jammu and Kashmir': 'in-jk',
    'Gujarat': 'in-gj',
    'Madhya Pradesh': 'in-mp',
    'Maharashtra': 'in-mh',
    'Dadra and Nagar Haveli and Daman and Diu': 'in-dh',
    'Bihar': 'in-br',
    'West Bengal': 'in-wb',
    'Jharkhand': 'in-jh',
    'Chhattisgarh': 'in-cg',
    'Odisha': 'in-od',
    'Kerala': 'in-kl',
    'Karnataka': 'in-ka',
    'Andhra Pradesh': 'in-ap',
    'Andaman and Nicobar Islands': 'in-an',
    'Assam': 'in-as',
    'Tripura': 'in-tr',
    'Arunachal Pradesh': 'in-ar',
    'Lakshadweep': 'in-ld',
    'Meghalaya': 'in-ml',
    'Manipur': 'in-mn',
    'Nagaland': 'in-nl',
    'Mizoram': 'in-mz',
    'Telangana': 'in-ts',
    'Ladakh': 'in-la',
    'Uttarakhand': 'in-uk',
    'Goa': 'in-ga',
  };
  
  export const getHcKey = (state: string): string => {
    return stateToHcKey[state] || 'unknown';
  };